config/routes.rb
Rails.application.routes.draw do
  # Locale switching route
  post "set_locale", to: "application#set_locale", as: :set_locale

  # ActiveStorage direct uploads
  # post '/rails/active_storage/direct_uploads', to: 'active_storage/direct_uploads#create', as: :rails_direct_uploads

  namespace :settings do
    resource :profile, only: [ :edit, :update ] do # Singular resource for profile
      patch :update_avatar
      delete :delete_avatar
      patch :update_theme
    end
    get "account", to: "settings#edit_account", as: "edit_account"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }
  get "/auth/:provider/callback", to: "sessions#google_auth"
  get "/auth/failure", to: redirect("/")

  get "dashboard", to: "dashboard#index"
  get "settings", to: "settings#index"

  resources :user_roles

  resources :role_permissions do
    collection do
      post :bulk_destroy
    end
  end

  resources :permissions do
    collection do
      post :bulk_destroy
    end
  end

  resources :roles do
    collection do
      post :bulk_destroy
    end
  end

  resources :categories do
    collection do
      post :bulk_destroy
    end
  end

  namespace :admin do
    resources :users do
      member do
        post :impersonate
      end
      collection do
        post :bulk_destroy
        post :stop_impersonating
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "pages#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable,
         :lockable, :timeoutable, :trackable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]
  has_one :profile, dependent: :destroy
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :categories, dependent: :destroy

  after_create :assign_default_role
  after_create :ensure_profile_exists
  after_create :set_profile_location

  attr_accessor :skip_password_validation
  attr_accessor :current_sign_in_ip_address

  accepts_nested_attributes_for :profile, update_only: true
  accepts_nested_attributes_for :user_roles, allow_destroy: true

  pg_search_scope :search_by_email,
              against: :email,
              using: {
                tsearch: { prefix: true } # Enables partial matches (e.g., "Admin" matches "Administrator")
              }

  def lock_access!
    update_columns(locked_at: Time.current, failed_attempts: 0)
  end

  def assign_default_role
    default_role = Role.fetch_default_role
    UserRole.create!(user: self, role: default_role) if default_role
  end

  def has_role?(role_name)
    roles.exists?(name: role_name)
  end

  def can?(action, resource)
    roles.joins(:role_permissions)
         .joins("INNER JOIN permissions ON permissions.id = role_permissions.permission_id")
         .where("permissions.name = ? AND permissions.resource = ?", action, resource)
         .exists?
  end

  def initial
    (profile&.display_name&.first || email.first).upcase
  end

  def set_profile_location
    return unless profile && current_sign_in_ip_address.present?
    profile.set_location_from_ip(current_sign_in_ip_address)
  end

  def ensure_profile_exists
    create_profile if profile.nil?
  end

  protected

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   before_action :set_user, only: %i[ show edit update destroy ]
   before_action :authorize_resource, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @pagy, @users = pagy(User.search_by_email(params[:query]), limit: params[:per_page] || "10")
    else
      @pagy, @users = pagy(User.all, limit: params[:per_page] || "10")
    end
    authorize @users
  end


  def show
  end

  def new
    @user = User.new
    @user.build_profile
  end

  def edit
    @user.build_profile unless @user.profile
  end

  def create
    @user = User.new(user_params)
    @user.skip_password_validation = true
    respond_to do |format|
      if @user.save
        flash[:notice] = "User was successfully created."
        format.turbo_stream { render turbo_stream: turbo_stream.refresh(request_id: nil) }
        format.html { redirect_to @user, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def bulk_destroy
    resource_ids = bulk_delete_params[:resource_ids] # Extract entry_ids from params
    respond_to do |format|
      if resource_ids.present?
        User.where(id: resource_ids).destroy_all
        format.html { redirect_to users_path, notice: "User was successfully destroyed." }
        format.turbo_stream { render turbo_stream: turbo_stream.refresh(request_id: nil) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @user.skip_password_validation = true
      lock_user
      # update_roles(@user)
      if @user.update(user_params)
        flash[:notice] = "User was successfully updated."
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.turbo_stream { render turbo_stream: turbo_stream.refresh(request_id: nil) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def impersonate
    authorize current_user

    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    def bulk_delete_params
      params.require(:bulk_delete).permit(resource_ids: [])
    end

    def authorize_resource
      authorize @user
    end

    def update_roles(user)
      user.roles = Role.where(id: params[:user][:role_ids].reject(&:blank?))
    end

    def lock_user
      if params[:locked] == "1"
        @user.lock_access! unless @user.access_locked?
      else
        @user.unlock_access! if @user.access_locked?
      end
    end

    def user_params
      params.require(:user).permit(
        :email,
        :locked,
        profile_attributes: [ :id, :first_name, :last_name, :gender ],
        role_ids: [] # This allows multiple role IDs to be assigned
      )
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb
require "open-uri"

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user_info = request.env["omniauth.auth"]

    # Find or create the user
    user = User.find_or_create_by(email: user_info["info"]["email"]) do |user|
      user.provider = user_info["provider"]
      user.uid = user_info["uid"]
      user.password = SecureRandom.hex(15) if user.encrypted_password.blank?
      user.skip_confirmation!
    end

    if user.persisted?
      # Create or update the profile for the user
      user.profile ||= user.build_profile(google_user(user_info))
      user.profile.save
      user.profile.attach_avatar(user_info["info"]["image"])
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      redirect_to new_user_registration_url, alert: "There was an issue signing in with Google."
    end
  end

  def google_user(user_info)
    {
      first_name: user_info["info"]["first_name"],
      last_name: user_info["info"]["name"].split.last # Extract last name from full name
    }
  end

  def github
    user_info = request.env["omniauth.auth"]

    # Find or create the user
    user = User.find_or_create_by(email: user_info["info"]["email"]) do |user|
      user.provider = user_info["provider"]
      user.uid = user_info["uid"]
      user.password = SecureRandom.hex(15) if user.encrypted_password.blank?
      user.skip_confirmation!
    end

    if user.persisted?
      # Create or update the profile for the user
      user.profile ||= user.build_profile(github_user(user_info))
      user.profile.save
      user.profile.attach_avatar(user_info["info"]["image"])
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      redirect_to new_user_registration_url, alert: "There was an issue signing in with GitHub."
    end
  end

  def github_user(user_info)
    {
      first_name: user_info["info"]["name"].split.first, # GitHub may not provide first name explicitly
      last_name: user_info["info"]["name"].split.last,  # Extract last name
      bio: user_info["info"]["bio"]                   # GitHub bio
    }
  end


  def failure
    redirect_to root_path, alert: "Google authentication failed."
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  before_action :configure_account_update_params, only: [ :update ]

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.current_sign_in_ip_address = request.remote_ip

    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :email, :password, :password_confirmation,
      profile_attributes: [ :first_name, :last_name, :gender, :location ]
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :email, :password, :password_confirmation, :current_password,
      profile_attributes: [
        :id, :first_name, :middle_name, :last_name, :gender, :bio,
        :phone_number, :date_of_birth, :location, :website, :social_links,
        :theme_preference, :timezone, :country_code, :postal_code
      ]
    ])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= styled_form_with model: @user, url: @user.new_record? ? admin_users_path : admin_user_path(@user), method: @user.new_record? ? :post : :patch, class: "space-y-4" do |f| %>
  <% if user.errors.any? %>
    <%= render "shared/form_errors" , model: user %>
  <% end %>
  <section class="space-y-2 overflow-hidden">
    <h2 class="text-lg font-bold text-gray-700">User Details</h2>
    <%= f.text_field :email, label: 'Email' , placeholder: 'Enter Email' %>
  </section>
    <section class="space-y-2 overflow-hidden">
      <h2 class="text-lg font-bold text-gray-700">Profile Details</h2>
      <%= f.fields_for :profile do |p| %>
        <%= p.text_field :first_name, label: 'First Name', placeholder: 'Enter First Name' %>
        <%= p.text_field :last_name, label: 'Last Name', placeholder: 'Enter Last Name' %>
        <%= p.select :gender,
                    Profile.genders.map { |key, _| [Profile::GENDER_DISPLAY[key.to_sym], key] },
                    { label: 'Gender' }
        %>
      <% end %>
    </section>
  <section class="space-y-2 overflow-hidden mt-2">
    <h2 class="text-lg font-bold text-gray-700">Roles</h2>
      <%= f.select :role_ids,
                    Role.pluck(:name, :id),
                    {
                      include_blank: false,
                      multiple: true,
                      label: "Select Roles (Use shift to select multiple)",
                    }
                   %>
  </section>

  <!-- Actions Section -->
  <section class="space-y-4 overflow-hidden">
    <h2 class="text-lg font-bold text-gray-700">Actions</h2>

    <div class="flex items-center gap-4">
  <%= label_tag :locked, "Lock" %>
  <%= check_box_tag :locked,
                    "1", # The value for the checkbox when checked
                    @user.access_locked?, # Checked if the user is locked
                    class: ["maybe-checkbox maybe-checkbox--light"],
                    data: { action: "bulk-select#toggleGroupSelection" } %>
</div>





  </section>

  <section>
    <%= f.submit 'Submit' %>
  </section>
<% end %>

app/views/admin/users/edit.html.erb
<%= modal_form_wrapper title: t(".update_user") do %>
  <%= render "form", user: @user %>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :user_management_tab do %>
  <%= render 'layouts/user_management_tab' %>
<% end %>
<div id="resources"
     data-controller="bulk-select"
     data-bulk-select-singular-label-value='resource'
     data-bulk-select-plural-label-value="resources"
     class="flex flex-col bg-white dark:bg-gray-800 dark:border-gray-600 rounded-xl border border-alpha-black-25 shadow-xs p-4">
  <div id="entry-selection-bar" data-bulk-select-target="selectionBar" class="flex justify-center hidden">
    <%= render partial: "shared/common/selection_bar", locals: { destroy_path: bulk_destroy_admin_users_path } %>
  </div>
  <div class="space-y-4">
    <h1 class="text-xl font-semibold text-gray-900 dark:text-white">Users</h1>
    <header class="flex justify-between items-center items-center">
      <div class="flex">
        <%= render partial: "shared/common/search_bar", locals: { resource_path: admin_users_path, resource_id: 'users-search', placeholder: 'Search users by email' } %>
      </div>
      <div class="flex">
        <% if can?(:create, User) %>
          <%= render(ButtonComponent.new(
            label: "Add User",
            href: new_admin_user_path,
            icon: "plus",
            variant: :default,
            turbo_frame: :modal
          )) %>
        <% end %>
      </div>
    </header>
    <div class="flex flex-col">
      <div class="shadow-md sm:rounded-lg">
        <div class="inline-block min-w-full align-middle">
          <div class="overflow-y-auto max-h-96">
            <table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-700">
              <thead class="bg-gray-100 dark:bg-gray-800 sticky top-0 z-10">
                <tr>
                  <% if can?(:create, User) %>
                    <th scope="col" class="p-4">
                      <div class="flex items-center">
                        <%= check_box_tag "selection_entry",
                class: "w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600",
                data: { action: "bulk-select#togglePageSelection" } %>
                      </div>
                    </th>
                  <% end %>
                  <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                    Email
                  </th>
                  <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                    Created At
                  </th>
                  <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                    Updated At
                  </th>
                  <th scope="col" class="p-4">
                    <span class="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-700">
                <% @users.each do |record| %>
                  <tr class="hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
                    <% if can?(:create, User) %>
                      <td class="p-4 w-4">
                        <% if can?(:create, User) %>
                          <div class="flex items-center">
                            <%= check_box_tag dom_id(record, "selection"),
                    class: "maybe-checkbox maybe-checkbox--light",
                    data: { id: record.id, "bulk-select-target": "row", action: "bulk-select#toggleRowSelection" } %>
                          </div>
                        <% end %>
                      </td>
                    <% end %>
                    <td class="py-4 px-6 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                      <%= record.email %>
                    </td>
                    <td class="py-4 px-6 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                      <%= record.created_at %>
                    </td>
                    <td class="py-4 px-6 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                      <%= record.updated_at %>
                    </td>
                    <% if can?(:create, User) %>
                      <td class="py-4 px-6 text-sm font-medium text-right whitespace-nowrap flex items-center space-x-4">
                        <%= link_to edit_admin_user_path(record),
                              data: { turbo_frame: :modal },
                              class: "text-gray-700 dark:text-white hover:text-blue-600 dark:hover:text-blue-400 transition-colors" do %>
                          <%= lucide_icon('square-pen', class: "w-5 h-5") %>
                        <% end %>
                        <%= render(ButtonComponent.new(
                          label: "Impersonate",
                          href: impersonate_admin_user_path(record),
                          variant: :danger,
                          method: :post,
                          data: { turbo_method: :post }
                        )) %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="p-4">
            <%= render "shared/pagination", pagy: @pagy %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= modal_form_wrapper title: t(".new_user") do %>
  <%= render "form", user: @user %>
<% end %>